# Generated by Django 3.2.12 on 2022-03-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uwuapp', '0002_auto_20220304_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
