# Generated by Django 3.2.12 on 2022-03-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uwuapp', '0003_chapter_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(),
        ),
    ]
