# Generated by Django 3.2.12 on 2022-03-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uwuapp', '0006_auto_20220307_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='uwuuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='uwuapp.Manga'),
        ),
    ]
