# Generated by Django 3.2.12 on 2022-03-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uwuapp', '0007_uwuuser_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isfavorite',
            name='manga_id',
        ),
        migrations.RemoveField(
            model_name='isfavorite',
            name='user_id',
        ),
        migrations.AddField(
            model_name='uwuuser',
            name='readed',
            field=models.ManyToManyField(blank=True, related_name='readed', to='uwuapp.Chapter'),
        ),
        migrations.DeleteModel(
            name='HasRead',
        ),
        migrations.DeleteModel(
            name='IsFavorite',
        ),
    ]
