# Generated by Django 3.2.12 on 2022-03-09 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uwuapp', '0010_auto_20220309_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uwuuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='uwuapp.Manga'),
        ),
        migrations.AlterField(
            model_name='uwuuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uwuuser',
            name='readed',
            field=models.ManyToManyField(blank=True, related_name='readed', to='uwuapp.Chapter'),
        ),
    ]
