# Generated by Django 3.2.12 on 2022-03-13 16:31

from django.db import migrations, models
import uwu.uwuapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('uwuapp', '0012_alter_uwuuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='image',
            field=models.ImageField(upload_to=uwu.uwuapp.models.upload_to),
        ),
    ]
