# Generated by Django 3.2.12 on 2022-03-13 16:36

from django.db import migrations, models
import uwu.uwuapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('uwuapp', '0013_alter_manga_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to=uwu.uwuapp.models.upload_to, verbose_name='Image'),
        ),
    ]
