# Generated by Django 3.2.12 on 2022-03-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uwuapp', '0014_alter_manga_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
