# Generated by Django 3.2.12 on 2022-03-14 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uwuapp', '0015_alter_manga_is_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='Readed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='uwuapp.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readed_user', to='uwuapp.uwuuser')),
            ],
        ),
        migrations.RemoveField(
            model_name='uwuuser',
            name='readed',
        ),
        migrations.AddField(
            model_name='uwuuser',
            name='readed',
            field=models.ManyToManyField(blank=True, related_name='readed', through='uwuapp.Readed', to='uwuapp.Chapter'),
        ),
    ]
