# Generated by Django 3.2.12 on 2022-03-16 08:05

from django.db import migrations, models
import uwu.uwuapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('uwuapp', '0018_uwuuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uwuuser',
            name='image',
            field=models.ImageField(default='images/default_user.png', upload_to=uwu.uwuapp.models.upload_to, verbose_name='Image'),
        ),
    ]
