# Generated by Django 3.2.12 on 2022-03-17 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uwuapp', '0019_alter_uwuuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manga',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
